name: build_and_test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything to determine version from git.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Install debian packages
        run: sudo apt-get install graphviz

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      # We have two cores so we can speed up the testing with xdist
      - name: Install xdist and openfiles
        run: uv pip install --system pytest-xdist pytest-cov

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Build and install
        run: uv pip install --system -v --no-deps -e .

      - name: Run tests
        run: |
          pytest -r a -v -n 3 --cov=astro_metadata_translator --cov=tests --cov-report=xml --cov-report=term --cov-branch \
            --junitxml=junit.xml -o junit_family=legacy

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Install documenteer
        run: uv pip install --system -r doc/requirements.txt

      - name: Build documentation
        if: ${{ matrix.python-version == '3.11' }}
        run: package-docs build -n -W

      - name: Landing page upload
        if: ${{ github.event_name == 'push' && matrix.python-version == '3.11' }}
        uses: lsst-sqre/ltd-upload@v1
        with:
          project: 'astro-metadata-translator'
          dir: 'doc/_build/html'
          password: ${{ secrets.LTD_PASSWORD }}
          username: ${{ secrets.LTD_USERNAME }}

  pypi:

    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything to embed the version.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build

      - name: Build and create distribution
        run: |
          python -m build --sdist --wheel

      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOADS }}
